import {Outfit} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const outfit = Outfit({
  subsets: ["latin"],
  weight:["400","500","600","700"]
});


export const metadata = {
  title: "Blog-APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.className}`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
